import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@radix-ui/themes/styles.css'
import { Theme } from '@radix-ui/themes'

import ReduxStoreProvider from '@_redux/index'
import Header from '@_components/Header'
import styles from './page.module.css'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Theme>
          <ReduxStoreProvider>
            <>
              <Header />
              <main className={styles.main}>
                <div className={styles.description}>{children}</div>
              </main>
            </>
          </ReduxStoreProvider>
        </Theme>
      </body>
    </html>
  )
}
